# Generated by Django 5.0.5 on 2024-05-29 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeautyHub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('komentar', models.TextField()),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BeautyHub.produk')),
            ],
        ),
    ]
