# Generated by Django 5.0.5 on 2024-07-06 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeautyHub', '0002_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPenjualan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_penjualan', models.DateTimeField(auto_now_add=True)),
                ('jumlah', models.PositiveIntegerField()),
                ('total_harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BeautyHub.produk')),
            ],
        ),
    ]
